# Generated by Django 3.2.4 on 2021-07-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0003_mygroup_group_id'),
        ('User', '0003_alter_user_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(to='Group.MyGroup'),
        ),
    ]
