# Generated by Django 3.2.4 on 2021-07-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0002_alter_event_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='actualTime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
