# Generated by Django 3.2.4 on 2021-07-25 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0005_alter_mygroup_group_id'),
        ('Calendar', '0004_remove_event_esttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Group.mygroup'),
        ),
        migrations.AlterField(
            model_name='event',
            name='method',
            field=models.CharField(choices=[('sync', 'Sync'), ('man', 'Manually')], default='sync', max_length=4),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
