# Generated by Django 3.2.5 on 2021-08-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0005_auto_20210725_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='details',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='method',
            field=models.CharField(choices=[('sync', 'Sync'), ('man', 'Manually')], default='sync', max_length=32),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('block', 'Block'), ('line', 'Line')], max_length=32),
        ),
    ]
