# Generated by Django 3.2.5 on 2021-08-11 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Calendar', '0007_alter_event_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='details',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='migrate', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('block', 'Block'), ('line', 'Line')], default='block', max_length=32),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
