version: "3.9"
services:
  web:
    build:
      context: ..
      dockerfile: deploy/frontend/Dockerfile
    # image: nginx:1.21.0
    # volumes:
    #   - ../frontend/rpi_smart_calendar/build:/usr/share/nginx/html:ro
    #   - ./nginx/templates:/etc/nginx/templates
    ports:
      - "80:80"
      # - "443:443"
    restart: always
    depends_on:
      - app

  app:
    build:
      context: ..
      dockerfile: deploy/python/Dockerfile
    expose:
      - "20001"
    environment:
      - PRODUCTION=true
      - SECRET_KEY
      - SUPERUSER_NAME
      - SUPERUSER_EMAIL
      - SUPERUSER_PASSWD
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    restart: always
    depends_on:
      - db

  db:
    image: postgres:13.3
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "20002:5432"
    expose:
      - "5432"
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - PGDATA=/var/lib/postgresql/data/pgdata

