version: "3.9"
services:
  web:
    image: nginx:1.21.0
    volumes:
      - ../frontend/rpi_smart_calendar/build:/usr/share/nginx/html:ro
      - ./nginx/templates:/etc/nginx/templates
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - app

  app:
    build:
      context: ..
      dockerfile: deploy/python/Dockerfile
    expose:
      - "20001"
    environment:
      - PRODUCTION
    restart: always
    depends_on:
      - db

  db:
    image: postgres:13.3
    volumes:
      - ./postgres/data:/var/lib/postgresql/data/pgdata
    ports:
      - "20002:5432"
    expose:
      - "5432"
    restart: always
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=django_db
      - PGDATA=/var/lib/postgresql/data/pgdata

