version: "3.9"
services:
  web:
    image: nginx:1.21.0
    volumes:
      - ../frontend/rpi_smart_calendar/build:/usr/share/nginx/html:ro
      - ./nginx/templates:/etc/nginx/templates
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - app

  app:
    build:
      context: ..
    expose:
      - "20001"
    restart: always
    depends_on:
      - db

  db:
    iamge: postgres:13.3
    volumes:
      - deploy/postgres/data:/var/lib/postgresql/data
    ports:
      -"20002:5432"
    expose:
      - "5432"
    restart: always
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=12345678
      - PGDATA=/var/lib/postgresql/data/pgdata

