# Generated by Django 3.2.4 on 2021-07-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0002_remove_mygroup_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mygroup',
            name='group_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
