# Generated by Django 3.2.4 on 2021-07-24 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calendar', '0002_alter_event_group'),
        ('Group', '0003_mygroup_group_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
