# Generated by Django 3.2.4 on 2021-07-23 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Group', '0003_auto_20210723_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Group.mygroup'),
        ),
        migrations.AlterField(
            model_name='course',
            name='group',
            field=models.ForeignKey(default='Event', on_delete=django.db.models.deletion.CASCADE, to='Group.mygroup'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
