# Generated by Django 3.2.4 on 2021-07-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0004_delete_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mygroup',
            name='group_id',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
